/*
 * Copyright 2014 Hieu Rocker
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.umeng.comm.ui.emoji;

/**
 * @author Hieu Rocker (rockerhieu@gmail.com)
 */
public class People {
    public static final EmojiBean[] DATA = new EmojiBean[]{
            EmojiBean.fromCodePoint(0x1f604),
            EmojiBean.fromCodePoint(0x1f603),
            EmojiBean.fromCodePoint(0x1f600),
            EmojiBean.fromCodePoint(0x1f60a),
            EmojiBean.fromChar((char) 0x263a),
            EmojiBean.fromCodePoint(0x1f609),
            EmojiBean.fromCodePoint(0x1f60d),
            EmojiBean.fromCodePoint(0x1f618),
            EmojiBean.fromCodePoint(0x1f61a),
            EmojiBean.fromCodePoint(0x1f617),
            EmojiBean.fromCodePoint(0x1f619),
            EmojiBean.fromCodePoint(0x1f61c),
            EmojiBean.fromCodePoint(0x1f61d),
            EmojiBean.fromCodePoint(0x1f61b),
            EmojiBean.fromCodePoint(0x1f633),
            EmojiBean.fromCodePoint(0x1f601),
            EmojiBean.fromCodePoint(0x1f614),
            EmojiBean.fromCodePoint(0x1f60c),
            EmojiBean.fromCodePoint(0x1f612),
            EmojiBean.fromCodePoint(0x1f61e),
            EmojiBean.fromCodePoint(0x1f623),
            EmojiBean.fromCodePoint(0x1f622),
            EmojiBean.fromCodePoint(0x1f602),
            EmojiBean.fromCodePoint(0x1f62d),
            EmojiBean.fromCodePoint(0x1f62a),
            EmojiBean.fromCodePoint(0x1f625),
            EmojiBean.fromCodePoint(0x1f630),
            EmojiBean.fromCodePoint(0x1f605),
            EmojiBean.fromCodePoint(0x1f613),
            EmojiBean.fromCodePoint(0x1f629),
            EmojiBean.fromCodePoint(0x1f62b),
            EmojiBean.fromCodePoint(0x1f628),
            EmojiBean.fromCodePoint(0x1f631),
            EmojiBean.fromCodePoint(0x1f620),
            EmojiBean.fromCodePoint(0x1f621),
            EmojiBean.fromCodePoint(0x1f624),
            EmojiBean.fromCodePoint(0x1f616),
            EmojiBean.fromCodePoint(0x1f606),
            EmojiBean.fromCodePoint(0x1f60b),
            EmojiBean.fromCodePoint(0x1f637),
            EmojiBean.fromCodePoint(0x1f60e),
            EmojiBean.fromCodePoint(0x1f634),
            EmojiBean.fromCodePoint(0x1f635),
            EmojiBean.fromCodePoint(0x1f632),
            EmojiBean.fromCodePoint(0x1f61f),
            EmojiBean.fromCodePoint(0x1f626),
            EmojiBean.fromCodePoint(0x1f627),
            EmojiBean.fromCodePoint(0x1f608),
            EmojiBean.fromCodePoint(0x1f62e),
            EmojiBean.fromCodePoint(0x1f62c),
            EmojiBean.fromCodePoint(0x1f610),
            EmojiBean.fromCodePoint(0x1f615),
            EmojiBean.fromCodePoint(0x1f62f),
            EmojiBean.fromCodePoint(0x1f636),
            EmojiBean.fromCodePoint(0x1f607),
            EmojiBean.fromCodePoint(0x1f60f),
            EmojiBean.fromCodePoint(0x1f611),
            EmojiBean.fromCodePoint(0x1f466),
            EmojiBean.fromCodePoint(0x1f467),
            EmojiBean.fromCodePoint(0x1f468),
            EmojiBean.fromCodePoint(0x1f63a),
            EmojiBean.fromCodePoint(0x1f638),
            EmojiBean.fromCodePoint(0x1f63b),
            EmojiBean.fromCodePoint(0x1f63d),
            EmojiBean.fromCodePoint(0x1f63c),
            EmojiBean.fromCodePoint(0x1f640),
            EmojiBean.fromCodePoint(0x1f63f),
            EmojiBean.fromCodePoint(0x1f639),
            EmojiBean.fromCodePoint(0x1f63e),
            EmojiBean.fromCodePoint(0x1f648),
            EmojiBean.fromCodePoint(0x1f649),
            EmojiBean.fromCodePoint(0x1f64a),
            EmojiBean.fromCodePoint(0x1f525),
            EmojiBean.fromChar((char) 0x2728),
            EmojiBean.fromCodePoint(0x1f440),
            EmojiBean.fromCodePoint(0x1f443),
            EmojiBean.fromCodePoint(0x1f444),
            EmojiBean.fromCodePoint(0x1f44d),
            EmojiBean.fromCodePoint(0x1f44e),
            EmojiBean.fromCodePoint(0x1f44c),
            EmojiBean.fromCodePoint(0x1f44a),
            EmojiBean.fromChar((char) 0x270a),
            EmojiBean.fromChar((char) 0x270c),
            EmojiBean.fromCodePoint(0x1f44b),
            EmojiBean.fromChar((char) 0x270b),
            EmojiBean.fromCodePoint(0x1f446),
            EmojiBean.fromCodePoint(0x1f447),
            EmojiBean.fromCodePoint(0x1f449),
            EmojiBean.fromCodePoint(0x1f448),
            EmojiBean.fromCodePoint(0x1f64c),
            EmojiBean.fromCodePoint(0x1f64f),
            EmojiBean.fromChar((char) 0x261d),
            EmojiBean.fromCodePoint(0x1f44f),
            EmojiBean.fromCodePoint(0x1f4aa),
            EmojiBean.fromCodePoint(0x1f48f),
            EmojiBean.fromCodePoint(0x1f491),
            EmojiBean.fromCodePoint(0x1f646),
            EmojiBean.fromCodePoint(0x1f645),
            EmojiBean.fromCodePoint(0x1f481),
            EmojiBean.fromCodePoint(0x1f64b),
            EmojiBean.fromCodePoint(0x1f486),
            EmojiBean.fromCodePoint(0x1f487),
            EmojiBean.fromCodePoint(0x1f485),
            EmojiBean.fromCodePoint(0x1f64e),
            EmojiBean.fromCodePoint(0x1f64d),
            EmojiBean.fromCodePoint(0x1f647),
            EmojiBean.fromCodePoint(0x1f451),
            EmojiBean.fromCodePoint(0x1f380),
            EmojiBean.fromCodePoint(0x1f302),
            EmojiBean.fromCodePoint(0x1f484),
            EmojiBean.fromCodePoint(0x1f49b),
            EmojiBean.fromCodePoint(0x1f499),
            EmojiBean.fromCodePoint(0x1f49c),
            EmojiBean.fromCodePoint(0x1f49a),
            EmojiBean.fromChar((char) 0x2764),
            EmojiBean.fromCodePoint(0x1f494),
            EmojiBean.fromCodePoint(0x1f49e),
            EmojiBean.fromCodePoint(0x1f349),
            EmojiBean.fromCodePoint(0x1f350),
            EmojiBean.fromCodePoint(0x1f351),
            EmojiBean.fromCodePoint(0x1f352),
            EmojiBean.fromCodePoint(0x1f354),
            EmojiBean.fromCodePoint(0x1f356),
            EmojiBean.fromCodePoint(0x1f360),
            EmojiBean.fromCodePoint(0x1f366),
            EmojiBean.fromCodePoint(0x1f370),
            EmojiBean.fromCodePoint(0x1f385),
            EmojiBean.fromCodePoint(0x1f3b1),
            EmojiBean.fromCodePoint(0x1f3b2),
            EmojiBean.fromCodePoint(0x1f40d),
            EmojiBean.fromCodePoint(0x1f414),
            EmojiBean.fromCodePoint(0x1f417),
            EmojiBean.fromCodePoint(0x1f418),
            EmojiBean.fromCodePoint(0x1f419),
            EmojiBean.fromCodePoint(0x1f420),
            EmojiBean.fromCodePoint(0x1f421),
            EmojiBean.fromCodePoint(0x1f422),
            EmojiBean.fromCodePoint(0x1f424),
            EmojiBean.fromCodePoint(0x1f426),
            EmojiBean.fromCodePoint(0x1f427),
            EmojiBean.fromCodePoint(0x1f428),
            EmojiBean.fromCodePoint(0x1f429),
            EmojiBean.fromCodePoint(0x1f42c),
            EmojiBean.fromCodePoint(0x1f42d),
            EmojiBean.fromCodePoint(0x1f42e),
            EmojiBean.fromCodePoint(0x1f42f),
            EmojiBean.fromCodePoint(0x1f430),
            EmojiBean.fromCodePoint(0x1f431),
            EmojiBean.fromCodePoint(0x1f432),
            EmojiBean.fromCodePoint(0x1f433),
            EmojiBean.fromCodePoint(0x1f434),
            EmojiBean.fromCodePoint(0x1f435),
            EmojiBean.fromCodePoint(0x1f436),
            EmojiBean.fromCodePoint(0x1f437),
            EmojiBean.fromCodePoint(0x1f438),
            EmojiBean.fromCodePoint(0x1f439),
            EmojiBean.fromCodePoint(0x1f43a),
            EmojiBean.fromCodePoint(0x1f43b),
            EmojiBean.fromCodePoint(0x1f43c),
            EmojiBean.fromCodePoint(0x1f43d),
            EmojiBean.fromCodePoint(0x1f469),
            EmojiBean.fromCodePoint(0x1f470),
            EmojiBean.fromCodePoint(0x1f471),
            EmojiBean.fromCodePoint(0x1f472),
            EmojiBean.fromCodePoint(0x1f473),
            EmojiBean.fromCodePoint(0x1f474),
            EmojiBean.fromCodePoint(0x1f475),
            EmojiBean.fromCodePoint(0x1f476),
            EmojiBean.fromCodePoint(0x1f477),
            EmojiBean.fromCodePoint(0x1f478),
            EmojiBean.fromCodePoint(0x1f493),
            EmojiBean.fromCodePoint(0x1f4a6),
            EmojiBean.fromCodePoint(0x1f4a8),
            EmojiBean.fromCodePoint(0x1f4a9),
            EmojiBean.fromCodePoint(0x1f680),
            EmojiBean.fromCodePoint(0x1f681),
            EmojiBean.fromCodePoint(0x1f682),
            EmojiBean.fromCodePoint(0x1f683),
            EmojiBean.fromCodePoint(0x1f684),
            EmojiBean.fromCodePoint(0x1f685),
            EmojiBean.fromCodePoint(0x1f688),
            EmojiBean.fromCodePoint(0x1f689),
            EmojiBean.fromCodePoint(0x1f690),
            EmojiBean.fromCodePoint(0x1f691),
            EmojiBean.fromCodePoint(0x1f692),
            EmojiBean.fromCodePoint(0x1f693),
            EmojiBean.fromCodePoint(0x1f696),
            EmojiBean.fromCodePoint(0x1f698),
            EmojiBean.fromChar((char)0x2122),
            EmojiBean.fromChar((char)0x2600),
            EmojiBean.fromChar((char)0x2601),
            EmojiBean.fromChar((char)0x2614),
            EmojiBean.fromChar((char)0x26a1),
            EmojiBean.fromChar((char)0x2744),
            
            EmojiBean.fromCodePoint(0x1f442),
            EmojiBean.fromCodePoint(0x1f48e),
            EmojiBean.fromCodePoint(0x1f495),
            EmojiBean.fromCodePoint(0x1f496),
            EmojiBean.fromCodePoint(0x1f498),
            EmojiBean.fromCodePoint(0x1f4a5)
    };
}
